apiVersion: v1
kind: Secret
metadata:
  name: weather-app-secrets
type: Opaque
data:
  # Replace YOUR_API_KEY with your base64 encoded OpenWeather API key
  openweather-api-key: NWMwMWMxY2E5M2MwMGZkZjQyNjIyN2IxMWRhNzQxOWE=